### ISSUE TITLE
Should we run RocksDB operations on the blocking pool?

### ISSUE THREAD

**Issue by iravid** [zio/zio-rocksdb#1]

**Comment by regiskuckaertz** [comment]
It looks like everything is asynchronous by default, though you can opt-in synchronous writes. So I'm tempted to say no except if 😅

**Comment by iravid** [comment]
Can you paste some references for posterity? 🙏🏻

**Comment by regiskuckaertz** [comment]
Ah yeah, from [the architecture docs](https://github.com/facebook/rocksdb/wiki/Basic-Operations#synchronous-writes):

> By default, each write to rocksdb is asynchronous: it returns after pushing the write from the process into the operating system. The transfer from operating system memory to the underlying persistent storage happens asynchronously. The sync flag can be turned on for a particular write to make the write operation not return until the data being written has been pushed all the way to persistent storage.

**Comment by iravid** [comment]
Ah, that's great. We don't directly expose the writing variants that use `WriteOptions`, so we don't have to deal with the presence/absence of sync. Maybe if/when we add those variants we can think about that.
