### ISSUE TITLE
Provide serialization/deserialization mechanisms

### ISSUE THREAD

**Issue by iravid** [zio/zio-rocksdb#2]

**Comment by regiskuckaertz** [comment]
I looked into RocksJava and all the operations take byte arrays. What was your idea here? A pair of functions `A => Chunk[Byte]` and `Chunk[Byte] => A`?

**Comment by iravid** [comment]
Yup.

**Comment by regiskuckaertz** [comment]
What do you think of having sth along the same lines as zio-config? Perhaps a bit more powerful to allow for schema evolution, I don't know if they did that.

**Comment by iravid** [comment]
The end goal should be something tailored to binary codecs. So something like the facilities that scodec provides would be best. But that's out of scope for this library. So I'd go for `Chunk[Byte] => RIO[R, A]` and `A => RIO[R, Chunk[Byte]]` for now as whatever we do eventually as `zio-codecs` would be reducible to that.

**Comment by mijicd** [comment]
Side note: a couple of us started to work on `zio-codec`, cc @sergei-shabanau @regis-leray (missing Eli's handle). As soon as we have the initial drafts I'll create repository and issues :).

**Comment by iravid** [comment]
@mijicd whee ❤️

**Comment by sergei-shabanau** [comment]
@soujiro32167 is Eli 🤗

**Comment by regiskuckaertz** [comment]
woohoo, this is great. Huh, I was going for something like this:
```scala
type Bytes = Chunk[Byte]
trait Encoder[-A] { self =>
  def apply[R](a: A): URIO[R, Bytes]
}
trait Decoder[+A] { self =>
  def decode[R](bytes: Bytes): ZIO[R, DecodeError, Result[A]]
}
trait Codec[A] extends Encoder[A] with Decoder[A]
```
Is this good enough for a start?

**Comment by iravid** [comment]
Yup. We did something similar for zio-kafka: https://github.com/zio/zio-kafka/tree/master/src/main/scala/zio/kafka/client/serde
Might make sense to use the same names.

**Comment by iravid** [comment]
Oh, I'd push the `R` up to the trait.

**Comment by sergei-shabanau** [comment]
Since I am one who works on invertible [parserz](https://github.com/spartanz/parserz) we also discussed the idea of having one `trait` that can expose two functions (going both ways).

**Comment by regiskuckaertz** [comment]
@sergei-shabanau Yes. Invertible parsers, I saw your talk 😄
