### ISSUE TITLE
Add support for WriteBatch

### ISSUE THREAD

**Issue by inbrain** [zio/zio-rocksdb#31]
WriteBatch seems to be a recommended way for initial data load into a rocks db, so I tried to cover its support. 
There are not one, but two alternative PRs for that
A simpler one is https://github.com/zio/zio-rocksdb/pull/29 .
A more advanced one is https://github.com/zio/zio-rocksdb/pull/30 which attempts to provide the same level of support to WriteBatch as is provided for RocksDb itself. Namely making it protected by ZManaged, as WriteBatch has to have its resources cleared. 
I personally prefer the second (more advanced) PR but there is problem with it. I had to expose Live type for ZManaged in RocksDB like this
```
def write(writeOptions: jrocks.WriteOptions, writeBatch: WriteBatch.Live): Task[Unit]
```
because I wanted to give it access to package private method `getUnderlying`
I don't know how acceptable that is, or if there are any suggestions how to use its trait, but still be able to do the same thing

In a larger scope: ColumnFamilyHandle should also be managed, I assume. As RocksDb documentation prescribes even the order of disposal related to corresponding rocks db instance disposal. So if some form of second version of WriteBatch PR is approved, I will probably be able to open a follow up PR for ColumnFamily handle

**Comment by mijicd** [comment]
Closed in #30
